export const getIngredientsForDish = (dishName: string): string[] => {
  const lowerDishName = dishName.toLowerCase().trim();
  
  const globalDishes: Record<string, string[]> = {
    // Asian Dishes
    "fried rice": ["rice", "vegetables", "egg", "soy sauce"],
    "sushi": ["rice", "fish", "seaweed", "vegetables"],
    "pad thai": ["rice noodles", "tofu", "peanuts", "bean sprouts", "lime"],
    "spring roll": ["rice paper", "vegetables", "shrimp", "herbs"],
    "dumplings": ["flour", "pork", "vegetables", "soy sauce"],
    "ramen": ["wheat noodles", "broth", "pork", "egg", "vegetables"],
    "biryani": ["rice", "meat", "yogurt", "saffron", "spices"],
    "curry": ["meat", "vegetables", "spices", "coconut milk"],
    "butter chicken": ["chicken", "tomato", "cream", "spices"],
    "samosa": ["flour", "potatoes", "peas", "spices"],
    "dal": ["lentils", "tomatoes", "spices", "ghee"],
    "naan": ["flour", "yogurt", "butter"],
    "kimchi": ["cabbage", "radish", "garlic", "chili"],
    "bibimbap": ["rice", "vegetables", "egg", "meat", "gochujang"],
    
    // European Dishes
    "pizza": ["flour", "tomato", "cheese", "toppings"],
    "pasta": ["wheat flour", "eggs", "sauce"],
    "lasagna": ["pasta", "cheese", "tomato sauce", "ground beef"],
    "risotto": ["rice", "broth", "cheese", "butter", "wine"],
    "paella": ["rice", "saffron", "seafood", "chicken", "vegetables"],
    "goulash": ["beef", "paprika", "vegetables", "potatoes"],
    "croissant": ["flour", "butter", "yeast"],
    "ratatouille": ["eggplant", "zucchini", "tomatoes", "bell peppers", "herbs"],
    "quiche": ["pastry", "eggs", "cream", "cheese", "fillings"],
    "moussaka": ["eggplant", "potatoes", "meat sauce", "béchamel"],
    
    // Middle Eastern & African Dishes
    "hummus": ["chickpeas", "tahini", "olive oil", "garlic", "lemon"],
    "falafel": ["chickpeas", "herbs", "spices"],
    "tabouleh": ["parsley", "bulgur", "tomato", "onion", "mint", "lemon"],
    "shawarma": ["meat", "flatbread", "vegetables", "sauce"],
    "couscous": ["semolina", "vegetables", "meat", "broth"],
    "tagine": ["meat", "fruits", "vegetables", "spices"],
    "injera": ["teff flour", "sourdough"],
    "jollof rice": ["rice", "tomatoes", "peppers", "spices"],
    
    // Latin American Dishes
    "tacos": ["tortilla", "meat", "vegetables", "cheese", "salsa"],
    "burrito": ["tortilla", "beans", "rice", "meat", "cheese", "vegetables"],
    "enchiladas": ["tortilla", "meat", "cheese", "sauce"],
    "guacamole": ["avocado", "tomato", "onion", "lime", "cilantro"],
    "ceviche": ["raw fish", "lime", "onion", "chili", "cilantro"],
    "empanadas": ["pastry", "meat", "vegetables", "cheese"],
    "pupusas": ["corn masa", "cheese", "beans", "meat"],
    "mole": ["chocolate", "chili", "spices", "nuts", "tomatoes"],
    
    // North American & Fusion
    "burger": ["bread", "beef patty", "cheese", "lettuce", "tomato"],
    "sandwich": ["bread", "meat", "cheese", "vegetables", "condiments"],
    "mac and cheese": ["pasta", "cheese", "milk", "butter"],
    "chicken wings": ["chicken", "sauce", "spices"],
    "poutine": ["fries", "cheese curds", "gravy"],
    "clam chowder": ["clams", "potatoes", "cream", "onions"],
    
    // Breakfast Items
    "pancakes": ["flour", "eggs", "milk", "sugar"],
    "waffles": ["flour", "eggs", "milk", "sugar", "butter"],
    "cereal": ["grains", "milk", "sugar"],
    "oatmeal": ["oats", "milk", "fruits", "nuts"],
    "french toast": ["bread", "eggs", "milk", "cinnamon", "sugar"],
    "omelette": ["eggs", "fillings", "cheese"],
    
    // Desserts
    "ice cream": ["milk", "cream", "sugar", "flavorings"],
    "cake": ["flour", "sugar", "eggs", "butter"],
    "cookies": ["flour", "sugar", "butter", "eggs"],
    "pie": ["pastry", "fillings", "sugar"],
    "cheesecake": ["cheese", "sugar", "eggs", "graham crackers"],
    "tiramisu": ["ladyfingers", "coffee", "mascarpone", "cocoa"],
    "baklava": ["phyllo dough", "nuts", "honey", "butter"],
    
    // Fast Food
    "french fries": ["potatoes", "oil", "salt"],
    "onion rings": ["onions", "batter", "oil"],
    "chicken nuggets": ["chicken", "breadcrumbs", "spices"],
    "hot dog": ["sausage", "bun", "condiments"],
    
    // Soups & Stews
    "chicken soup": ["chicken", "vegetables", "broth", "noodles"],
    "tomato soup": ["tomatoes", "cream", "broth", "herbs"],
    "minestrone": ["vegetables", "beans", "pasta", "broth"],
    "borscht": ["beets", "cabbage", "potatoes", "meat", "sour cream"],
    "stew": ["meat", "vegetables", "broth", "potatoes"],
    "chili": ["beans", "meat", "tomatoes", "chili peppers"],
    
    // Salads
    "caesar salad": ["romaine lettuce", "croutons", "parmesan", "dressing"],
    "greek salad": ["tomatoes", "cucumber", "olives", "feta", "olive oil"],
    "potato salad": ["potatoes", "mayonnaise", "vegetables", "eggs"],
    "coleslaw": ["cabbage", "carrots", "mayonnaise", "vinegar"],
    
    // Snacks & Appetizers
    "nachos": ["tortilla chips", "cheese", "toppings"],
    "popcorn": ["corn kernels", "butter", "salt"],
    "pretzels": ["flour", "salt", "yeast"],
    "mozzarella sticks": ["mozzarella", "breadcrumbs", "marinara sauce"],
    
    // Indian dishes
    "dosa": ["rice", "lentils", "potato filling", "chutney", "sambar"],
    "idli": ["rice", "lentils", "sambhar", "chutney"],
    "vada": ["lentils", "spices", "herbs"],
    "poha": ["flattened rice", "onions", "turmeric", "peanuts"],
    "paratha": ["wheat flour", "stuffing", "ghee"],
    "rajma": ["kidney beans", "tomatoes", "spices"],
    "chole": ["chickpeas", "tomatoes", "spices"],
    "upma": ["semolina", "vegetables", "spices"],
    "pav bhaji": ["mixed vegetables", "tomatoes", "butter", "bread"],
    "dhokla": ["gram flour", "yogurt", "spices"],
    "khichdi": ["rice", "lentils", "ghee", "spices"],
    "sambhar": ["lentils", "vegetables", "tamarind", "spices"],
    "rasam": ["tamarind", "tomatoes", "spices"],
    "ladoo": ["gram flour", "sugar", "ghee"],
    "gulab jamun": ["milk solids", "sugar syrup", "cardamom"],
    "jalebi": ["flour", "sugar syrup", "saffron"],
    "barfi": ["milk", "sugar", "nuts"],
    "rasgulla": ["cheese", "sugar syrup"],
    "chaat": ["fried dough", "potatoes", "chickpeas", "yogurt", "chutneys"],
    "pani puri": ["fried hollow puri", "flavored water", "potato filling"],
    "pakora": ["vegetables", "gram flour batter", "spices"],
    "bhel puri": ["puffed rice", "vegetables", "chutneys", "sev"],
    "aloo tikki": ["potatoes", "spices", "chutneys"]
  };
  
  return globalDishes[lowerDishName] || [];
};

export const foodNameVariations: Record<string, string> = {
  "maize": "corn",
  "sweetcorn": "corn",
  "white potatoes": "potatoes",
  "sweet potato": "sweet potatoes",
  "sweet potatoes": "sweet potatoes",
  "pumpkin": "pumpkin",
  "carrot": "carrots",
  "squash": "squash",
  "red sweet pepper": "red bell pepper",
  "red bell pepper": "bell pepper",
  "kale": "kale",
  "spinach": "spinach",
  "tomato": "tomatoes",
  "onion": "onions",
  "eggplant": "eggplant",
  "ripe mango": "mango",
  "cantaloupe": "cantaloupe",
  "apricot": "apricots",
  "ripe papaya": "papaya",
  "dried peach": "peaches",
  "beef": "beef",
  "pork": "pork",
  "lamb": "lamb",
  "goat": "goat",
  "rabbit": "rabbit",
  "game": "game meat",
  "chicken": "chicken",
  "duck": "duck",
  "fresh fish": "fish",
  "dried fish": "fish",
  "shellfish": "shellfish",
  "dried beans": "beans",
  "dried peas": "peas",
  "lentils": "lentils",
  "nuts": "nuts",
  "seeds": "seeds",
  "milk": "milk",
  "cheese": "cheese",
  "yogurt": "yogurt",
  "oil": "oil",
  "fats": "fats",
  "butter": "butter",
  "sugar": "sugar",
  "honey": "honey",
  "chocolates": "chocolate",
  "candies": "candy",
  "cookies": "cookie",
  "cakes": "cake",
  "black pepper": "pepper",
  "salt": "salt",
  "soy sauce": "soy sauce",
  "hot sauce": "hot sauce",
  "coffee": "coffee",
  "tea": "tea",
  "alcoholic beverages": "alcohol",
  "bread": "bread",
  "noodles": "noodles",
  "porridge": "porridge",
  "grain products": "grains",
  "white yam": "yam",
  "white cassava": "cassava",
  "foods made from roots": "roots",
  "amaranth": "amaranth",
  "cassava leaves": "cassava leaves",
  "ripe mango": "mango",
  "cantaloupe": "cantaloupe",
  "apricot": "apricots",
  "ripe papaya": "papaya",
  "dried peach": "peaches",
  "liver": "liver",
  "kidney": "kidney",
  "heart": "heart",
  "organ meats": "organ meat",
  "blood-based foods": "blood",
  "eggs from chicken": "eggs",
  "eggs from duck": "eggs",
  "eggs from guinea fowl": "eggs",
  "hummus": "hummus",
  "peanut butter": "peanut butter",
  "milk products": "dairy",
  "sweetened soda": "soda",
  "sweetened juice drinks": "juice",
  "sugary foods": "sweets",
  "wheat flour": "flour",
  "rice": "rice",
  "chapati": "roti",
  "roti": "roti",
  "dal makhani": "dal",
  "paneer butter masala": "paneer",
  "palak paneer": "paneer",
  "aloo gobi": "aloo",
  "baingan bharta": "baingan",
  "matar paneer": "paneer",
  "chana masala": "chana",
  "veg biryani": "biryani",
  "veg pulao": "pulao",
  "gajar ka halwa": "halwa",
  "sooji halwa": "halwa",
  "besan ladoo": "ladoo",
  "motichoor ladoo": "ladoo",
  "rasmalai": "rasmalai",
  "kheer": "kheer",
  "lassi": "lassi",
  "chaas": "chaas",
  "shikanji": "shikanji",
  "nimbu pani": "nimbu pani",
  "jal jeera": "jal jeera",
  "aam panna": "aam panna",
  "thandai": "thandai",
  "masala chai": "chai",
  "adrak chai": "chai",
  "elaichi chai": "chai",
  "pudina chai": "chai",
  "tulsi chai": "chai",
  "dalia": "dalia",
  "khichri": "khichri",
  "upma": "upma",
  "poha": "poha",
  "idli sambar": "idli",
  "dosa sambar": "dosa",
  "vada sambar": "vada",
  "uttapam": "uttapam",
  "aloo paratha": "paratha",
  "gobi paratha": "paratha",
  "paneer paratha": "paratha",
  "mooli paratha": "paratha",
  "methi paratha": "paratha",
  "pyaaz paratha": "paratha",
  "dal paratha": "paratha",
  "sattu paratha": "paratha",
  "aloo tikki chaat": "aloo tikki",
  "papri chaat": "chaat",
  "dahi bhalla": "dahi bhalla",
  "sev puri": "puri",
  "bhel puri": "puri",
  "pani puri": "puri",
  "raj kachori": "kachori",
  "samosa chaat": "samosa",
  "aloo chaat": "aloo",
  "chana chaat": "chana",
  "dahi puri": "puri",
  "masala puri": "puri",
  "sev tameta": "sev",
  "dhokla": "dhokla",
  "khandvi": "khandvi",
  "fafda": "fafda",
  "thepla": "thepla",
  "khakhra": "khakhra",
  "gathiya": "gathiya",
  "sev": "sev",
  "chivda": "chivda",
  "chakri": "chakri",
  "shankarpali": "shankarpali",
  "mathri": "mathri",
  "namakpare": "namakpare",
  "murukku": "murukku",
  "seedai": "seedai",
  "thattai": "thattai",
  "ribbon pakoda": "pakoda",
  "manoharam": "manoharam",
  "thenkuzhal": "thenkuzhal",
  "adhirasam": "adhirasam",
  "mysore pak": "mysore pak",
  "jangiri": "jangiri",
  "badusha": "badusha",
  "soan papdi": "soan papdi",
  "balushahi": "balushahi",
  "imarti": "imarti",
  "ghevar": "ghevar",
  "pheni": "pheni",
  "khaja": "khaja",
  "chirote": "chirote",
  "kajjikayalu": "kajjikayalu",
  "poornam boorelu": "boorelu",
  "ariselu": "ariselu",
  "gavvalu": "gavvalu",
  "sunnundalu": "sunnundalu",
  "bobbatlu": "bobbatlu",
  "kudumulu": "kudumulu",
  "undrallu": "undrallu",
  "paramannam": "paramannam",
  "daddojanam": "daddojanam",
  "pulihora": "pulihora",
  "bisi bele bath": "bisi bele bath",
  "vangi bath": "vangi bath",
  "sambar rice": "sambar",
  "rasam rice": "rasam",
  "curd rice": "curd",
  "lemon rice": "lemon",
  "tomato rice": "tomato",
  "coconut rice": "coconut",
  "tamarind rice": "tamarind",
  "mango rice": "mango",
  "mint rice": "mint",
  "coriander rice": "coriander",
  "jeera rice": "jeera",
  "ghee rice": "ghee",
  "kashmiri pulao": "pulao",
  "peas pulao": "pulao",
  "vegetable pulao": "pulao",
  "mushroom pulao": "pulao",
  "paneer pulao": "pulao",
  "tava pulao": "pulao",
  "chicken biryani": "biryani",
  "mutton biryani": "biryani",
  "egg biryani": "biryani",
  "fish biryani": "biryani",
  "prawn biryani": "biryani",
  "hyderabadi biryani": "biryani",
  "lucknowi biryani": "biryani",
  "kolkata biryani": "biryani",
  "thalassery biryani": "biryani",
  "dindigul biryani": "biryani",
  "ambur biryani": "biryani",
  "kalyani biryani": "biryani",
  "beary biryani": "biryani",
  "memoni biryani": "biryani",
  "bombay biryani": "biryani",
  "sindhi biryani": "biryani",
  "afghani biryani": "biryani",
  "irani biryani": "biryani",
  "yakhni pulao": "pulao",
  "mutter pulao": "pulao",
  "kashmiri pulao": "pulao",
  "vegetable korma": "korma",
  "paneer butter masala": "paneer",
  "palak paneer": "paneer",
  "malai kofta": "kofta",
  "navratan korma": "korma",
  "shahi paneer": "paneer",
  "dum aloo": "aloo",
  "aloo gobi": "aloo",
  "baingan bharta": "baingan",
  "bhindi masala": "bhindi",
  "chana masala": "chana",
  "matar paneer": "paneer",
  "dal makhani": "dal",
  "dal tadka": "dal",
  "dal fry": "dal",
  "rajma masala": "rajma",
  "chole bhature": "chole",
  "kadhi pakora": "kadhi",
  "sarson ka saag": "sarson",
  "makki di roti": "roti",
  "missi roti": "roti",
  "bajra roti": "roti",
  "jowar roti": "roti",
  "ragi roti": "roti",
  "thepla": "thepla",
  "khakhra": "khakhra",
  "bhakri": "bhakri",
  "akki roti": "roti",
  "jolada roti": "roti",
  "thalipeeth": "thalipeeth",
  "puran poli": "poli",
  "bakharkhani": "bakharkhani",
  "sheermal": "sheermal",
  "taftan": "taftan",
  "kulcha": "kulcha",
  "naan": "naan",
  "rumali roti": "roti",
  "parotta": "parotta",
  "lachha paratha": "paratha",
  "butter naan": "naan",
  "garlic naan": "naan",
  "peshawari naan": "naan",
  "keema naan": "naan",
  "aloo naan": "naan",
  "paneer naan": "naan",
  "gobi naan": "naan",
  "methi naan": "naan",
  "pyaaz naan": "naan",
  "dal naan": "naan",
  "sattu naan": "naan",
  "aloo tikki": "tikki",
  "papri chaat": "chaat",
  "dahi bhalla": "bhalla",
  "sev puri": "puri",
  "bhel puri": "puri",
  "pani puri": "puri",
  "raj kachori": "kachori",
  "samosa chaat": "samosa",
  "aloo chaat": "chaat",
  "chana chaat": "chaat",
  "dahi puri": "puri",
  "masala puri": "puri",
  "sev tameta": "sev",
  "dhokla": "dhokla",
  "khandvi": "khandvi",
  "fafda": "fafda",
  "thepla": "thepla",
  "khakhra": "khakhra",
  "gathiya": "gathiya",
  "sev": "sev",
  "chivda": "chivda",
  "chakri": "chakri",
  "shankarpali": "shankarpali",
  "mathri": "mathri",
  "namakpare": "namakpare",
  "murukku": "murukku",
  "seedai": "seedai",
  "thattai": "thattai",
  "ribbon pakoda": "pakoda",
  "manoharam": "manoharam",
  "thenkuzhal": "thenkuzhal",
  "adhirasam": "adhirasam",
  "mysore pak": "mysore pak",
  "jangiri": "jangiri",
  "badusha": "badusha",
  "soan papdi": "soan papdi",
  "balushahi": "balushahi",
  "imarti": "imarti",
  "ghevar": "ghevar",
  "pheni": "pheni",
  "khaja": "khaja",
  "chirote": "chirote",
  "kajjikayalu": "kajjikayalu",
  "poornam boorelu": "boorelu",
  "ariselu": "ariselu",
  "gavvalu": "gavvalu",
  "sunnundalu": "sunnundalu",
  "bobbatlu": "bobbatlu",
  "kudumulu": "kudumulu",
  "undrallu": "undrallu",
  "paramannam": "paramannam",
  "daddojanam": "daddojanam",
  "pulihora": "pulihora",
  "bisi bele bath": "bisi bele bath",
  "vangi bath": "vangi bath",
  "sambar rice": "sambar",
  "rasam rice": "rasam",
  "curd rice": "curd",
  "lemon rice": "lemon",
  "tomato rice": "tomato",
  "coconut rice": "coconut",
  "tamarind rice": "tamarind",
  "mango rice": "mango",
  "mint rice": "mint",
  "coriander rice": "coriander",
  "jeera rice": "jeera",
  "ghee rice": "ghee",
  "kashmiri pulao": "pulao",
  "peas pulao": "pulao",
  "vegetable pulao": "pulao",
  "mushroom pulao": "pulao",
  "paneer pulao": "pulao",
  "tava pulao": "pulao",
  "chicken biryani": "biryani",
  "mutton biryani": "biryani",
  "egg biryani": "biryani",
  "fish biryani": "biryani",
  "prawn biryani": "biryani",
  "hyderabadi biryani": "biryani",
  "lucknowi biryani": "biryani",
  "kolkata biryani": "biryani",
  "thalassery biryani": "biryani",
  "dindigul biryani": "biryani",
  "ambur biryani": "biryani",
  "kalyani biryani": "biryani",
  "beary biryani": "biryani",
  "memoni biryani": "biryani",
  "bombay biryani": "biryani",
  "sindhi biryani": "biryani",
  "afghani biryani": "biryani",
  "irani biryani": "biryani",
  "yakhni pulao": "pulao",
  "mutter pulao": "pulao",
  "kashmiri pulao": "pulao",
  "vegetable korma": "korma",
  "paneer butter masala": "paneer",
  "palak paneer": "paneer",
  "malai kofta": "kofta",
  "navratan korma": "korma",
  "shahi paneer": "paneer",
  "dum aloo": "aloo",
  "aloo gobi": "aloo",
  "baingan bharta": "baingan",
  "bhindi masala": "bhindi",
  "chana masala": "chana",
  "matar paneer": "paneer",
  "dal makhani": "dal",
  "dal tadka": "dal",
  "dal fry": "dal",
  "rajma masala": "rajma",
  "chole bhature": "chole",
  "kadhi pakora": "kadhi",
  "sarson ka saag": "sarson",
  "makki di roti": "roti",
  "missi roti": "roti",
  "bajra roti": "roti",
  "jowar roti": "roti",
  "ragi roti": "roti",
  "thepla": "thepla",
  "khakhra": "khakhra",
  "bhakri": "bhakri",
  "akki roti": "roti",
  "jolada roti": "roti",
  "thalipeeth": "thalipeeth",
  "puran poli": "poli",
  "bakharkhani": "bakharkhani",
  "sheermal": "sheermal",
  "taftan": "taftan",
  "kulcha": "kulcha",
  "naan": "naan",
  "rumali roti": "roti",
  "parotta": "parotta",
  "lachha paratha": "paratha",
  "butter naan": "naan",
  "garlic naan": "naan",
  "peshawari naan": "naan",
  "keema naan": "naan",
  "aloo naan": "naan",
  "paneer naan": "naan",
  "gobi naan": "naan",
  "methi naan": "naan",
  "pyaaz naan": "naan",
  "dal naan": "naan",
  "sattu naan": "naan",
  "aloo tikki": "tikki",
  "papri chaat": "chaat",
  "dahi bhalla": "bhalla",
  "sev puri": "puri",
  "bhel puri": "puri",
  "pani puri": "puri",
  "raj kachori": "kachori",
  "samosa chaat": "samosa",
  "aloo chaat": "chaat",
  "chana chaat": "chaat",
  "dahi puri": "puri",
  "masala puri": "puri",
  "sev tameta": "sev",
  "dhokla": "dhokla",
  "khandvi": "khandvi",
  "fafda": "fafda",
  "thepla": "thepla",
  "khakhra": "khakhra",
  "gathiya": "gathiya",
  "sev": "sev",
  "chivda": "chivda",
  "chakri": "chakri",
  "shankarpali": "shankarpali",
  "mathri": "mathri",
  "namakpare": "namakpare",
  "murukku": "murukku",
  "seedai": "seedai",
  "thattai": "thattai",
  "ribbon pakoda": "pakoda",
  "manoharam": "manoharam",
  "thenkuzhal": "thenkuzhal",
  "adhirasam": "adhirasam",
  "mysore pak": "mysore pak",
  "jangiri": "jangiri",
  "badusha": "badusha",
  "soan papdi": "soan papdi",
  "balushahi": "balushahi",
  "imarti": "imarti",
  "ghevar": "ghevar",
  "pheni": "pheni",
  "khaja": "khaja",
  "chirote": "chirote",
  "kajjikayalu": "kajjikayalu",
  "poornam boorelu": "boorelu",
  "ariselu": "ariselu",
  "gavvalu": "gavvalu",
  "sunnundalu": "sunnundalu",
  "bobbatlu": "bobbatlu",
  "kudumulu": "kudumulu",
  "undrallu": "undrallu",
  "paramannam": "paramannam",
  "daddojanam": "daddojanam",
  "pulihora": "pulihora",
  "bisi bele bath": "bisi bele bath",
  "vangi bath": "vangi bath",
  "sambar rice": "sambar",
  "rasam rice": "rasam",
  "curd rice": "curd",
  "lemon rice": "lemon",
  "tomato rice": "tomato",
  "coconut rice": "coconut",
  "tamarind rice": "tamarind",
  "mango rice": "mango",
  "mint rice": "mint",
  "coriander rice": "coriander",
  "jeera rice": "jeera",
  "ghee rice": "ghee",
  "kashmiri pulao": "pulao",
  "peas pulao": "pulao",
  "vegetable pulao": "pulao",
  "mushroom pulao": "pulao",
  "paneer pulao": "pulao",
  "tava pulao": "pulao",
  "chicken biryani": "biryani",
  "mutton biryani": "biryani",
  "egg biryani": "biryani",
  "fish biryani": "biryani",
  "prawn biryani": "biryani",
  "hyderabadi biryani": "biryani",
  "lucknowi biryani": "biryani",
  "kolkata biryani": "biryani",
  "thalassery biryani": "biryani",
  "dindigul biryani": "biryani",
  "ambur biryani": "biryani",
  "kalyani biryani": "biryani",
  "beary biryani": "biryani",
  "memoni biryani": "biryani",
  "bombay biryani": "biryani",
  "sindhi biryani": "biryani",
  "afghani biryani": "biryani",
  "irani biryani": "biryani",
  "yakhni pulao": "pulao",
  "mutter pulao": "pulao",
  "kashmiri pulao": "pulao",
  "vegetable korma": "korma",
  "paneer butter masala": "paneer",
  "palak paneer": "paneer",
  "malai kofta": "kofta",
  "navratan korma": "korma",
  "shahi paneer": "paneer",
  "dum aloo": "aloo",
  "aloo gobi": "aloo",
  "baingan bharta": "baingan",
  "bhindi masala": "bhindi",
  "chana masala": "chana",
  "matar paneer": "paneer",
  "dal makhani": "dal",
  "dal tadka": "dal",
  "dal fry": "dal",
  "rajma masala": "rajma",
  "chole bhature": "chole",
  "kadhi pakora": "kadhi",
  "
